### ISSUE TITLE
RuntimeError: Unknown property type: Collection

### ISSUE THREAD

**Issue by luckyraul** [ruby-odata/odata#10]
I guess I need to create some kind of mapping to this type? or what? 

```
<d:Товары m:type="Collection(StandardODATA.Document_СчетНаОплатуПокупателю_Товары_RowType)">
        <d:element m:type="StandardODATA.Document_СчетНаОплатуПокупателю_Товары_RowType">
            <d:Ref_Key>2457995c-796f-11e5-ec89-fa163edef683</d:Ref_Key>
            <d:LineNumber>1</d:LineNumber>
            <d:Номенклатура_Key>32f56234-8174-11e5-be93-fa163edef683</d:Номенклатура_Key>
            <d:Содержание>Mannn</d:Содержание>
            <d:Количество>1</d:Количество>
            <d:Цена>234000</d:Цена>
            <d:Сумма>234000</d:Сумма>
            <d:ПроцентСкидки>0</d:ПроцентСкидки>
            <d:СуммаСкидки>0</d:СуммаСкидки>
            <d:СтавкаНДС>БезНДС</d:СтавкаНДС>
            <d:СуммаНДС>0</d:СуммаНДС>
        </d:element>
    </d:Товары>
```

**Comment by plainprogrammer** [comment]
That is likely. The gem has support for Complex Types: https://github.com/ruby-odata/odata/blob/master/spec/odata/complex_type_spec.rb

However, a lot of OData service implementations actually extend the spec with new "core" data types that are not simply grokkable with the basic Compex Type support. So, you may have to create your own property mappings. This is possible, but not documented, currently. You can look at the core properties that the gem already supports for examples: https://github.com/ruby-odata/odata/tree/master/lib/odata/properties

And, you will have to register any custom properties you setup with the OData::PropertyRegistry so that they can be automatically dealt with: https://github.com/ruby-odata/odata/blob/master/lib/odata/properties.rb
