### ISSUE TITLE
Insert/update functionality

### ISSUE THREAD

**Issue by luckyraul** [ruby-odata/odata#9]
Is it available?

**Comment by plainprogrammer** [comment]
Yes, an `OData::EntitySet` behaves like a hash and supports insert and update via the 'shovel' method: https://github.com/ruby-odata/odata#entities

I would advise against using this gem in production unless you have intentions of actively contributing back to the project, because there are a number of gaps in terms of capabilities. I no longer work for the company where I originally developed this and am not actively maintaining it. But, I am happy to review and accept pull requests.
